clc
clear all
close all

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Directional Coupler Half Ring
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

data_path   = 'D:\Ligentic_NU_1_TapeOut_April2026\results_data\Data_directional_coupler';
cd(data_path);

T = readtable('Kappa2_vs_gap_n1.97_R25_W1200nm.csv');
T.Properties.VariableNames
T = sortrows(T, {'G', 'E'});

% figure(1)
% clf;
% hold on;
% CLs = unique(T.CL)
% for i = 1:length(CLs)
%     m = T.CL == CLs(i);
%     plot(T.G(m), T.Kappa_sq(m), '-o', 'LineWidth', 1, 'MarkerSize', 4, 'MarkerFaceColor', 'auto', 'DisplayName', sprintf('Lc = %d µm', CLs(i)));
% end
% xlabel('Gap (nm)');
% ylabel('\kappa^2');
% legend('Location','best');
% title(sprintf('R = %d µm | W = %d nm', T.R(1), T.W(1)));
% hold off
% grid on;

T = sortrows(T, {'E', 'G'});

CLs = unique(T.CL);
Es  = unique(T.E);
nPerFig = 6;
nFigs = ceil(length(CLs) / nPerFig);

for f = 1:nFigs
    figure(f); clf; hold on;
    idx = (f-1)*nPerFig+1 : min(f*nPerFig, length(CLs));
    for i = idx
        for j = 1:length(Es)
            m = T.CL == CLs(i) & T.E == Es(j);
            if sum(m) == 0, continue; end
            if Es(j) == 1
                style = '-o';
            else
                style = '--s';
            end
            plot(T.G(m), T.Kappa_sq(m), style, LineWidth=1.5, MarkerSize=8, ...
                MarkerFaceColor="auto",...
                DisplayName=sprintf('Lc=%d µm | E=%d', CLs(i), Es(j)));
        end
    end
    xlabel('Gap (nm)'); ylabel('\kappa^2');
    legend('Location','best');
    title(sprintf('R = %d µm | W = %d nm | Lc %d–%d µm', ...
        T.R(1), T.W(1), CLs(idx(1)), CLs(idx(end))));
    grid on; hold off;
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Directional Coupler - Pulley 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
pulley_data_path = 'D:\Ligentic_NU_1_TapeOut_April2026\results_data\Data_directional_coupler_Pulley';
cd(pulley_data_path);

% Ensure the filename matches the format generated by your sweep
T_pulley = readtable('DC_Pulley_Kappa2_vs_gap_n1.97_R25_W1600nm_WIO1200nm.csv');
T_pulley = sortrows(T_pulley, {'E', 'G'});

% E_to_plot = [1]; 
% 
% CLs = unique(T_pulley.CL);
% % --- CHANGE 2: Filter Es based on your selection ---
% Es  = intersect(unique(T_pulley.E), E_to_plot); 

% figure(10); 
% clf; 
% hold on;
% for i = 1:length(CLs)
%     for j = 1:length(Es)
%         m = T_pulley.CL == CLs(i) & T_pulley.E == Es(j); 
%         if sum(m) == 0, continue; end
% 
%         style = '-o'; 
%         if Es(j) == 0, style = '--s'; end
% 
%         plot(T_pulley.G(m), T_pulley.Kappa_sq(m), style, 'LineWidth', 1.5, ...
%             'MarkerSize', 8, 'MarkerFaceColor', 'auto', ...
%             'DisplayName', sprintf('Lc=%d µm | E=%d', CLs(i), Es(j)));
%     end
% end
% xlabel('Gap (nm)'); 
% ylabel('\kappa^2');
% legend('Location','best');
% title(sprintf('Pulley \\kappa^2 | R = %d µm | W = %d nm', T_pulley.R(1), T_pulley.W(1))); 
% grid on; hold off;
% 
% 
% figure(11); 
% clf; 
% hold on;
% for i = 1:length(CLs)
%     for j = 1:length(Es)
% 
%         m = T_pulley.CL == CLs(i) & T_pulley.E == Es(j); 
%         if sum(m) == 0, continue; end
% 
%         style = '-o'; 
%         if Es(j) == 0, style = '--s'; end
% 
%         plot(T_pulley.G(m), T_pulley.Loss(m), style, 'LineWidth', 1.5, ...
%             'MarkerSize', 8, 'MarkerFaceColor', 'auto', ...
%             'DisplayName', sprintf('Lc=%d µm | E=%d', CLs(i), Es(j))); 
%     end
% end
% xlabel('Gap (nm)'); 
% ylabel('Loss (dB)');
% legend('Location','best');
% title(sprintf('Pulley Loss | R = %d µm | W = %d nm', T_pulley.R(1), T_pulley.W(1)));
% grid on; hold off;
% 
% pulley_data_path = 'D:\Ligentic_NU_1_TapeOut_April2026\results_data\Data_directional_coupler_Pulley';
% cd(pulley_data_path);
% 
% % Ensure the filename matches the format generated by your sweep
% T_pulley = readtable('DC_Pulley_Kappa2_vs_gap_n1.97_R25_W1600nm.csv');
% T_pulley = sortrows(T_pulley, {'E', 'G'});
% 
E_to_plot = [1]; 

CLs = unique(T_pulley.CL);
Es  = intersect(unique(T_pulley.E), E_to_plot); 

my_colors = turbo(length(CLs)); 

figure(10); clf; hold on;
for i = 1:length(CLs)
    for j = 1:length(Es)
        m = T_pulley.CL == CLs(i) & T_pulley.E == Es(j); 
        if sum(m) == 0, continue; end

        style = '-o'; 
        if Es(j) == 0, style = '--s'; end

        plot(T_pulley.G(m), T_pulley.Kappa_sq(m), style, 'LineWidth', 1.5, ...
            'MarkerSize', 8, 'MarkerFaceColor', 'auto', ...
            'Color', my_colors(i, :), ... 
            'DisplayName', sprintf('Lc=%d µm | E=%d', CLs(i), Es(j))); 
    end
end
xlabel('Gap (nm)'); 
ylabel('\kappa^2');
legend('Location','best');
title(sprintf('Pulley \\kappa^2 | R = %d µm | W = %d nm | WIO = 1200 nm ', T_pulley.R(1), T_pulley.W(1))); 
%title(sprintf('Pulley \\kappa^2 | R = %d µm | W = %d nm ', T_pulley.R(1), T_pulley.W(1)));
grid on; hold off;


figure(11); clf; hold on;
for i = 1:length(CLs)
    for j = 1:length(Es)
        m = T_pulley.CL == CLs(i) & T_pulley.E == Es(j); 
        if sum(m) == 0, continue; end
        
        style = '-o'; 
        if Es(j) == 0, style = '--s'; end
        
        plot(T_pulley.G(m), T_pulley.Loss(m), style, 'LineWidth', 1.5, ...
            'MarkerSize', 8, 'MarkerFaceColor', 'auto', ...
            'Color', my_colors(i, :), ... 
            'DisplayName', sprintf('Lc=%d µm | E=%d', CLs(i), Es(j))); 
    end
end
xlabel('Gap (nm)'); 
ylabel('Loss (dB)');
legend('Location','best');
title(sprintf('Pulley Loss | R = %d µm | W = %d nm', T_pulley.R(1), T_pulley.W(1)));
grid on; hold off;

%--------------------------------------------------------------------------
% 4. Loss vs. Coupling Length (Specific Gaps: 300nm, 600nm)
%--------------------------------------------------------------------------
figure(13); clf; hold on;

target_gaps = [300, 600];
target_Es   = [0, 1];

% Generate distinct colors for the specific Gaps we are plotting
gap_colors = lines(length(target_gaps)); 

for g = 1:length(target_gaps)
    for e = 1:length(target_Es)
        % Filter for the specific Gap and Euler state
        m = T_pulley.G == target_gaps(g) & T_pulley.E == target_Es(e);
        if sum(m) == 0, continue; end
        
        % CRITICAL: Sort by Coupling Length (CL) so the line plot connects smoothly left-to-right
        sub_T = sortrows(T_pulley(m, :), 'CL');
        
        style = '-o'; 
        if target_Es(e) == 0, style = '--s'; end
        
        plot(sub_T.CL, sub_T.Loss, style, 'LineWidth', 1.5, ...
            'MarkerSize', 8, 'MarkerFaceColor', 'auto', ...
            'Color', gap_colors(g, :), ...
            'DisplayName', sprintf('Gap=%d nm | E=%d', target_gaps(g), target_Es(e)));
    end
end

xlabel('Coupling Length, L_c (\mum)'); 
ylabel('Loss (dB)');
legend('Location','best');
title(sprintf('Pulley Loss vs L_c | R = %d µm | W = %d nm', T_pulley.R(1), T_pulley.W(1)));
grid on; hold off;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% J
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% figure(2)
% clf;
% hold on;
% for i = 1:length(CLs)
%     m = T.CL == CLs(i);
%     plot(T.G(m), T.Loss(m), '-o', 'LineWidth', 1, 'MarkerSize', 4, 'MarkerFaceColor', 'auto', 'DisplayName', sprintf('Lc = %d µm', CLs(i)));
% end
% xlabel('Gap (nm)');
% ylabel('Loss (dB)');
% legend('Location','best');
% title(sprintf('R = %d µm | W = %d nm', T.R(1), T.W(1)));
% grid on;

% figure(3)
% clf;
% hold on;
% c  = 3e8;
% ng = 2.1394;
% vg = c / ng
% R  = 25e-6;
% 
% for i = 1:length(CLs)
%     m  = T.CL == CLs(i);
%     Lc = CLs(i) * 1e-6;
%     L  = 2*pi*R + 4*Lc;          % Lcx = Lcy = Lc
%     Kappa_sq_squre = T.Kappa_sq(m) ;          % fraction
%     J  = (Kappa_sq_squre / 2) .* (vg/L) / 1e9;  % GHz
%     plot(T.G(m), J,  '-o', 'LineWidth', 1, 'MarkerSize', 4, 'MarkerFaceColor', 'auto', 'DisplayName', sprintf('Lc = %d µm', CLs(i)));
% end
% xlabel('Gap (nm)');
% ylabel('J (GHz)');
% legend('Location','best');
% title(sprintf('R = %d µm | W = %d nm', T.R(1), T.W(1)));
% grid on;
% 
% figure(4)
% clf;
% hold on;
% m0 = T.CL == CLs(1);
% plot(T.G(m0), T.Kappa_sq(m0),'-x','LineWidth', 1);
% xlabel('Gap (nm)');
% ylabel('\kappa^2');
% legend('Location','best');
% title(sprintf('R = %d µm | W = %d nm', T.R(1), T.W(1)));
% hold off
% grid on;
%%
% figure(5)
% clf
% m0 = T.CL == CLs(1);
% Lc = CLs(1) * 1e-6;
% L  = 2*pi*R + 4*Lc;          % Lcx = Lcy = Lc
% Kappa_sq_squre = T.Kappa_sq(m0) ;          % fraction
% J(m0)  = (Kappa_sq_squre / 2) .* (vg/L) / 1e9;  % GHz
% plot(T.G(m0), J, '-x', 'LineWidth', 1.2, 'MarkerSize', 4);
% xlabel('Gap (nm)');
% ylabel('J (GHz)');
% legend('Location','best');
% grid on;
